### ISSUE TITLE
Filepaths for actions filepaths normalized

### ISSUE THREAD

**Issue by Ekrekr** [dataform-co/dataform#1703]
To reproduce:

`definitions/folder/actions.yaml`:
```yaml
actions:
- table:
    fileName: "../content.sql"
```

results in the compiled graph having the fileName of `definitions/foleder/../content.sql` for the action.
